version: 0.2

phases:
  pre_build:
    commands:
      - echo logging in to amazon ECR...
      - aws --version
      - REPOSITORY_URI=296475210819.dkr.ecr.ap-south-1.amazonaws.com/aws-pipeline
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Build phase started on 'date'
      - echo Building the jar file using maven 
      # - mvn clean package
      # - echo Building the Docker image
      # - docker build -t $REPOSITORY_URI:latest .
      # - docker tag aws-pipeline:latest 296475210819.dkr.ecr.ap-south-1.amazonaws.com/aws-pipeline:latest
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes
