version: 0.2

phases:
  pre_build:
    commands:
      - echo logging in to amazon ECR...
      - aws --version
      - REPOSITORY_URI=296475210819.dkr.ecr.ap-south-1.amazonaws.com/aws-pipeline
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - docker build -t aws-pipeline .
      - docker tag aws-pipeline:latest 296475210819.dkr.ecr.ap-south-1.amazonaws.com/aws-pipeline:latest
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes
